package servlet;

import java.util.Date;

import javax.inject.Inject;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;

import dao.TaskDao;
import entity.Task;

@WebServlet(loadOnStartup = 2, name = "initServlet", value = "/initServlet")
public class AppConfigServlet extends HttpServlet {

	private static final long serialVersionUID = 2151250503543054202L;

	@Inject
	private TaskDao dao;

	@Override
	public void init() throws ServletException {
		super.init();

		System.out.println("==== Initial Configuration for the Context ====");
		System.out.println("==== Database Context Initialization ====");

		createSampleTask();

		System.out.println("==== Database Context Initialized ====");
	}

	private void createSampleTask() {
		for (int i = 0; i < 20; i++) {
			Task t = Task.builder().name("Task " + i).assignedTo("User").dueDate(new Date())
					.description("record generated by system").build();
			dao.save(t);
		}
	}

}
