package servlet;

import java.util.Date;

import javax.inject.Inject;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;

import dao.TaskDao;
import entity.Task;

@WebServlet(loadOnStartup = 2, name = "initServlet", value = "/initServlet")
public class AppConfigServlet extends HttpServlet{

	private static final long serialVersionUID = 2151250503543054202L;
	
	@Inject
	private TaskDao dao;
	
	@Override
	public void init() throws ServletException {
		super.init();
		
		System.out.println("==== Initial Configuration for the Context ====");
		System.out.println("==== Database Context Initialization ====");
		
		createSampleTask();

		System.out.println("==== Database Context Initialized ====");
	}

	private void createSampleTask() {
		Task t = new Task();
		t.setName("New Task Example");
		t.setAssignedTo("User");
		t.setDueDate(new Date());
		t.setDescription("record generated by system");
		dao.save(t);
	}

}
